package com.aniket.domain;

public enum NotificationType {
    STORE_REGISTERED,
    STORE_APPROVED,
    STORE_REJECTED,
    STORE_BLOCKED,
    STORE_UNBLOCKED,
    STORE_DELETED,
    SUBSCRIPTION_APPROVED,
    SUBSCRIPTION_REJECTED,
    PROFILE_UPDATED,
    SYSTEM_ALERT,
    ORDER_CREATED,
    LOW_STOCK_ALERT,
    REFUND_CREATED,
    SHIFT_STARTED,
    SHIFT_ENDED,
    EMPLOYEE_ADDED
}
